dist: xenial
sudo: required
language: ruby
branches:
  only:
    - fyi-next
rvm:
  - 2.5 # Latest official 2.5.x
  - 2.6 # Latest official 2.6.x
  - ruby-head
gemfile:
  - Gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.6
    - rvm: ruby-head
services:
  - postgresql
cache:
  - bundler
before_install:
  - sudo add-apt-repository --remove 'http://us-central1.gce.archive.ubuntu.com/ubuntu/ main restricted'
  - sudo add-apt-repository --remove 'http://us-central1.gce.archive.ubuntu.com/ubuntu/ universe'
  - sudo add-apt-repository --remove 'http://us-central1.gce.archive.ubuntu.com/ubuntu/ multiverse'
  - sudo add-apt-repository http://archive.ubuntu.com/ubuntu/
  - sudo add-apt-repository 'http://archive.ubuntu.com/ubuntu/ universe'
  - sudo add-apt-repository 'http://archive.ubuntu.com/ubuntu/ multiverse'
  - sudo apt-get -qq update
  - sudo locale-gen --no-archive en_GB
  - sudo locale-gen --no-archive en_GB.UTF-8
  - sudo update-locale
  - git submodule update --init --recursive
  - psql -c "create database template_utf8 template template0 encoding 'UTF-8';" -U postgres
  - psql -c "update pg_database set datistemplate=true where datname='template_utf8';" -U postgres
  - psql -c "create database foi_test template template_utf8;" -U postgres
  - cp config/database.yml-test config/database.yml
  - cp config/general.yml-example config/general.yml
  - cp config/newrelic.yml-example config/newrelic.yml
  - sudo apt-get update
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y install exim4-daemon-light
  - sudo apt-get -y install `cut -d " " -f 1 config/packages | egrep -v "(^#|wkhtml|bundler|^ruby$|^ruby1.9.1$|^rubygems$|^rake)"`
  - gem install bundler -v '< 2.0'
  - RAILS_ENV=test ./script/rails-post-deploy
  - psql -c 'CREATE COLLATION "en_GB" (LOCALE = "en_GB.utf8");' -U postgres foi_test
  - psql -c 'CREATE COLLATION "en_GB.utf8" (LOCALE = "en_GB.utf8");' -U postgres foi_test
  - psql -c 'CREATE COLLATION "en" (LOCALE = "en_GB.utf8");' -U postgres foi_test
  - RAILS_ENV=test ./script/update-xapian-index
install: echo 'Bundle installed through script/rails-post-deploy'
notifications:
  email:
    recipients:
      - nigel+travis@fyi.org.nz
